config/routes.rb
Rails.application.routes.draw do
  resources :likes
  get 'sessions/bundle'
  get 'sessions/install'
  resources :selected_activities
  resources :activities
  resources :countries, only: [:index, :show]
  resources :trip_countries
  resources :trips
  resources :users
  resources :reviews

  get "/africa", to: "countries#africa", as: "africa"
  get "/asia", to: "countries#asia", as: "asia"
  get "/europe", to: "countries#europe", as: "europe"
  get "/oceania", to: "countries#oceania", as: "oceania"
  get "/north_america", to: "countries#north_america", as: "north_america"
  get "/south_america", to: "countries#south_america", as: "south_america"
  get "/search", to: "countries#search", as: "search"

  get "/", to: "users#home", as: "home"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "sessions", to: "sessions#create", as: "sessions"
  delete "sessions", to: "sessions#destroy"
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :trip_countries
  has_many :countries, through: :trip_countries
  has_many :selected_activities, through: :trip_countries

  def self.mine
    @user = User.find_by(id: session[:user_id])
    self.all.select{|trip| trip.user_id == @user.id}
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show]
  before_action :authorized

  def index
    @trips = Trip.all
    if logged_in?
      @trips = current_user.trips
    else
    end
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.valid?
      @trip.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def show
    @countries = @trip.countries
    @page_hash = {}
    @countries.each{|country| @page_hash[country.name] = []}
    @trip.selected_activities.each{|sa| @page_hash[sa.trip_country.country.name] << sa.activity}
    @trip_country = TripCountry.new
    @selected_activity = SelectedActivity.new
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :start_date, :end_date, :travel_companions, :notes, :user_id)
  end

  def set_trip
    @trip = Trip.find(params[:id])
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/index.html.erb
<!-- Jumbotron style for the heading -->
<div class="container pt-4">
  <img src="images/airport.jpeg" class="card-img-top rounded" alt="Sunglasses on the sand">
</div>

  <div class="container">
    <div class="">
      <span class = "lead d-flex justify-content-between align-items-center">
        <h1 class="display-4 mt-3 ">Wanderlust </h1>
      <a href="/trips/new" class="btn btn-info">Plan A New Trip</a>
      </span>
      <p class="lead d-flex justify-content-between">Quit your job, buy a ticket, get a tan fall in love, never return
        <button type="button" class="btn btn-warning"><%= link_to 'Reviews', reviews_path, :class => "text-white" %></button>
      </p>
    </div>

<div class="container">
  <div class="row">
    <% @trips.each do |trip| %>
    <br>
    <div class="col-sm-3 py-4">
      <div class="card text-center">
        <img src="https://images.unsplash.com/photo-1515622472995-1a06094d2224?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjQ0MTA5fQ&auto=format&fit=crop&w=500&q=80" class="card-img-top" alt="Suitcase with Camera">
        <div class="card-body">
          <h5 class="card-title"><%= trip.name %></h5>
          <p class="card-text"><%= trip.start_date.strftime("%B %-d, %Y")%></p>
          <!-- Link to the countries show page -->
          <a href="/trips/<%=trip.id%>" class="btn btn-dark">Proceed to Gate</a>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/trips/new.html.erb
<div class="container">
  <br>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
    <h2 class="text-danger">There were some errors:</h2>
    <ul>
      <% @trip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
    </div>
  <% end %>
  <br>
  <h1 class="text-success">Plan a New Trip: </h1>
  <%= form_for @trip do |f| %>
    <div class="form-row">
      <div class="form-group col-md-6">
      <%= f.hidden_field :user_id, value: @trip.user_id %>
      <%= f.text_field :name, :class => "form-control text-secondary", :placeholder => "Trip Name" %>
      </div>
      <div class="form-group col-md-6">
      <%= f.text_field :travel_companions, :class => "form-control text-secondary", :placeholder => "Travel Companions" %>
      </div>
      <div class="form-group col-md-6">
      <%= f.label "Starts"%>
      <%= f.date_field :start_date%>
      </div>
      <div class="form-group col-md-6">
      <%= f.label "Ends"%>
      <%= f.date_field :end_date%>
      </div>
      <div class="form-group col-md-6">
        <div class="input-group mb-4">
          <div class="input-group-prepend">
            <label class="input-group-text" for="inputGroupSelect01">Country</label>
          </div>
          <%= f.collection_select :country_ids, Country.all, :id, :name, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group col-md-6">
      <%= f.text_area :notes, :class => "form-control text-secondary", :placeholder => "Notes" %>
      </div>
      <div class="form-group col-md-6">
      <%=  f.submit class: "btn btn-info" %>
      <% end %>
      </div>
    </div>
</div>

app/views/trips/show.html.erb
<!-- Jumbotron style for the heading -->
<div class="container pt-4">
  <div class="jumbotron text-center">
    <div class="container">
      <div class="row">
        <div class="col">
          <h1 class="display-4"><%= @trip.name%></h1>
          <p class="lead"><%= @trip.start_date.strftime("%B %-d, %Y")%> <i class="fas fa-arrow-right"></i> <%= @trip.end_date.strftime("%B %-d, %Y")%> </p>
          <% if @trip.travel_companions != nil %>
            <p class="lead">Travelling with <%= @trip.travel_companions%></p>
            <span class="lead">Travelling to <% @trip.countries.each do |country|%> <%= country.name %>, <% end %></span>
            <% end %>
            <div class="container">
              <%= form_for @trip_country do |f| %>
              <%= f.hidden_field :trip_id, value: @trip.id %>
              <%= f.collection_select(:country_id, Country.all, :id, :name) %>
              <%= f.submit "Add A Country", class: "btn btn-outline-info m-2"%>
              <% end %>
            </div>
          </div>
          <div class="col-4">
            <img src="https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" class="card-img-top" alt="Sunglasses on the sand">
          </div>
        </div>
      </div>
  </div>
</div>
<div class="container">
  <br>
  <div class="row">
    <% @page_hash.each do |country, activities| %>
    <br>
    <div class="col-5 pb-4">
      <div class="card text-center">
      <img src="<%= @countries.find{|c| c.name == country}.country_image%>" class="card-img-top" alt="European City">
        <div class="card-body">
        <h5 class="card-title"><%= country %></h5>
          <p class="card-text">You're off to great places, today is your day! Your mountain is waiting... So get on your way!.</p>
          <!-- Link to the countries show page -->
          <a href="/countries/<%= @countries.find{|c| c.name == country}.id%>" class="btn btn-warning">Vist <%= country %></a>
        </div>
      </div>
    </div>
    <div class="col-7 text-center">
      <br>
      <h1 class="text-dark">Activities: </h1>
          <% activities.each do |activity| %>
            <p><%= link_to activity.name, activity_path(activity) %></p>
          <% end %>
          <%= form_for @selected_activity do |f| %>
          <% @tripid = TripCountry.find_by(trip_id: @trip.id, country_id: @countries.find{|c| c.name == country}.id)%>
          <%= f.hidden_field :trip_country_id, value: @tripid.id %>
          <%= f.collection_select(:activity_id, Activity.activities_for_country(country), :id, :name) %>
          <%= f.submit "Add An Activity", class: "btn btn-outline-info m-2" %>
          <% end %>
        </div>
    <% end %>
  </div>
</div>