config/routes.rb
Rails.application.routes.draw do
  resources :likes
  get 'sessions/bundle'
  get 'sessions/install'
  resources :selected_activities
  resources :activities
  resources :countries, only: [:index, :show]
  resources :trip_countries
  resources :trips
  resources :users
  resources :reviews

  get "/africa", to: "countries#africa", as: "africa"
  get "/asia", to: "countries#asia", as: "asia"
  get "/europe", to: "countries#europe", as: "europe"
  get "/oceania", to: "countries#oceania", as: "oceania"
  get "/north_america", to: "countries#north_america", as: "north_america"
  get "/south_america", to: "countries#south_america", as: "south_america"
  get "/search", to: "countries#search", as: "search"

  get "/", to: "users#home", as: "home"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "sessions", to: "sessions#create", as: "sessions"
  delete "sessions", to: "sessions#destroy"
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :country
  has_many :selected_activities
  has_many :reviews
  has_many :likes, through: :reviews
  has_many :trip_countries, through: :selected_activities
  has_many :trips, through: :trip_countries
  has_many :users, through: :reviews



  def self.activities_per_country(country_id)
    self.all.select{|activity| activity.country_id == country_id}
  end

  def self.activities_for_country(country_name)
    self.all.select{|activity| activity.country.name == country_name}
  end

  def activity_review_length
      self.reviews.length
  end

  def activity_review_sum
      all_ratings = self.reviews.map { |review| review.rating }.sum
      
  end

  def average_rating
    if self.activity_review_sum == 0 || self.activity_review_length == 0
        "Awaiting Reviews"
    else
      average = self.activity_review_sum / self.activity_review_length
    end
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authorized
  skip_before_action :authorized, only: [:index, :show]


  def index
    @activities = Activity.all
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.valid?
      @activity.save
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def show
    @review_id = 
    @reviews = @activity.reviews
    @like = Like.new
    @review = Review.new
    if logged_in?
      @user = current_user.id
    else
    end
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      redirect_to activity_path(@activity)
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to activitys_path
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :price, :notes, :street_name, :city, :zip_code, :country_id, :image)
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/index.html.erb
<!-- Jumbotron style for the heading -->
<div class="container pt-4">
  <div class="jumbotron text-center">
    <h1 class="display-4">The World is Your Oyster</h1>
    <p class="lead">Explore the activities for inspiration</p>
    <button type="button" class="btn btn-outline-dark"><%= link_to 'Or Create New Activity', new_activity_path, :class => "text-dark" %></button>
  </div>
</div>
<!-- Each statment to print out a card style box for each continent with image. -->


<div class="container">
  <br>
  <div class="row">
    <% @activities.each do |activity| %>
    <br>
    <div class="col-sm-3 pt-4">
      <div class="card text-center">
        <img src="<%= activity.image%>" class="card-img-top" alt="European City">
        <div class="card-body">
          <h5 class="card-title"><%= activity.name %></h5>
          <p class="card-text"><%= activity.notes.truncate_words(20) %></p>
          <hr>
          <% if activity.reviews.length == 0 %>
          <i class="fas fa-question"></i>
          <p>No Reviews Yet</p>
          <% elsif %>
          <p class="card-text">Average Rating:
                <% if activity.average_rating == "Awaiting Reviews" %>
                  <i class="far fa-angry text-danger"></i>
                <% elsif activity.average_rating == nil %>
                  <i class="fas fa-question"></i>
                <% elsif activity.average_rating == 1 %>
                  <i class="fas fa-star text-warning"></i>
                <% elsif activity.average_rating == 2 %>
                  <i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i>
                <% elsif activity.average_rating == 3 %>
                  <i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i>
                <% elsif activity.average_rating == 4 %>
                  <i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i>
                <% elsif activity.average_rating == 5 %>
                  <i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i>
                <%end%></p>
                <%end  %>
          <!-- Link to the countries show page -->
          <%= link_to "Read More...", activity_path(activity), :class => "btn btn-info"%>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/activities/new.html.erb
<div class="container">
  <br>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
    <h2 class="text-danger">There were some errors:</h2>
    <ul>
      <% @activity.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
    </div>
    <% end %>
  <br>
  <h1 class="text-success">Add a new activity: </h1>
  <%= form_for @activity do |f| %>
    <div class="form-row">
      <div class="form-group col-md-6">
      <%= f.text_field :name, :class => "form-control text-dark", :placeholder => "Activity Name" %>
      </div>
      <div class="form-group col-md-6">
      <%= f.text_field :price, :class => "form-control text-dark", :placeholder => "Price: £" %>
      </div>
      <div class="form-group col-md-6">
      <%= f.text_field :street_name, :class => "form-control text-dark", :placeholder => "Street Address : 172, Fairfield way" %>
      </div>
      <div class="form-group col-md-6">
      <%= f.text_field :city, :class => "form-control text-dark", :placeholder => "City" %>
      </div>
      <div class="form-group col-md-6">
      <%= f.text_field :zip_code, :class => "form-control text-dark", :placeholder => "Zip Code" %>
      </div>
      <div class="form-group col-md-6">
      <%= f.text_field :notes, :class => "form-control text-dark", :placeholder => "Description:" %>
      </div>
      <div class="form-group col-md-6">
      <%= f.collection_select :country_id, Country.all, :id, :name, :class => "form-control text-dark"%>
      </div>
      <%=  f.submit class: "btn btn-info" %>
      <% end %>
    </div>

app/views/activities/show.html.erb
<div class="container pt-4">
  <div class="jumbotron text-center">
    <div class="container">
      <div class="row">
        <div class="col">
          <h1 class="display-4"><%= @activity.name %></h1>
          <p class="lead">- In <%= @activity.country.name %></p>
        </div>
        <div class="col-4">
          <% if @activity.image %>
          <img src="<%= @activity.image%>" class="img-fluid rounded mx-auto d-block" alt="<%= @activity.name%>'s Activity">
          <% else %>
          <img src="http://b-vlaw.com/wp-content/uploads/2018/07/DD-Coming-Soon-Retro-Style-Background-56400-Preview.jpg" class="img-fluid rounded mx-auto d-block" alt=" Coming Soon">
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mb-3">
  <div class="row">
    <div class="col-sm-9">
      <h2 class="text-warning"> Description: </h2>
      <h3 class="text-muted"><%= @activity.notes%></h3>
    </div>
    <div class="col-sm-3">
      <h5 class="card-title text-right"> Address: </h5>
      <p class="card-text text-right text-muted">
      <%= @activity.street_name%> <br>
      <%= @activity.city%> <br>
      <%= @activity.zip_code%>
      <br>
      <p class="card-text text-right text-muted"> Price: £<%= @activity.price%> </p>
      <p class="card-text text-right text-muted"> Average Rating Score: <br><%= @activity.average_rating %> </p>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3">
    </div>
  </div>
</div>

<div class="container my-5">
  <h2 class="text-warning">Reviews: </h2>
  <% if current_user %>
  <div class="container">
    <% if @review.errors.any? %>
      <div id="error_explanation">
      <h2 class="text-danger">There were some errors:</h2>
      <ul>
        <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      </div>
      <% end %>
    <h4 class="text-success">Add a new review: </h4>
    <%= form_for @review do |f| %>
      <div class="form-row">

        <div class="form-group col-md-6">
        <%= f.hidden_field :user_id, value: @user %>
        <%= f.hidden_field :activity_id, value: @activity.id %>
        <%= f.text_field :title, :class => "form-control text-secondary", :placeholder => "Review Title" %>
        </div>
        <div class="form-group col-md-6">
        <%= f.text_field :rating, :class => "form-control text-secondary", :placeholder => "Rating - 1 to 5" %>
        </div>
        <div class="form-group col-md-6">
        <%= f.text_field :review, :class => "form-control text-secondary", :placeholder => "Review" %>
        </div>
        <div class="form-group col-md-6">
        </div>
        <%=  f.submit class: "btn btn-info" %>
        <% end %>
      </div>
      <% else %>
    <% end %>

<%  if @activity.reviews.length >= 1 %>
    <% @reviews.each do |review| %>
      <div class="card text-center my-4">
      <div class="card-header text-left text-muted d-flex justify-content-between">
        <span class="font-italic"> Written on <%= review.created_at.strftime("%B %-d, %Y") %></span>
        <%= review.user.name %>
      </div>
        <div class="card-body">
          <p class="card-text"><%= review.title %></p>
          <p class="card-text"><%= review.review%></p>
          <p class="card-text">
          <% if review.rating == 0 %>
            <i class="far fa-angry"></i>
          <% elsif review.rating == nil %>
            <i class="fas fa-question"></i>
          <% elsif review.rating == 1 %>
            <i class="fas fa-star text-warning"></i>
          <% elsif review.rating == 2 %>
            <i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i>
          <% elsif review.rating == 3 %>
            <i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i>
          <% elsif review.rating == 4 %>
            <i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i>
          <% elsif review.rating == 5 %>
            <i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i>
          <%end%>
          </p>
        </div>
        <% if logged_in? %>
          <div class="card-footer text-muted d-flex justify-content-between">
            <p> <%= review.likes.count %> Likes</p>

            <% if review.user.name == current_user.name %>
              <%= form_tag "/reviews/#{review.id}", method: 'delete' do %>
              <%= hidden_field_tag "activity_id", @activity.id %>
              <%= submit_tag "Delete", class: "btn btn-outline-secondary"%>
              <% end %>

            <% else %>
            <% end %>

            <%= form_tag likes_path, method: 'post' do %>
            <%= hidden_field_tag "activity_id", @activity.id %>
            <%= hidden_field_tag "like[review_id]", review.id %>
            <%= button_tag type: 'submit', class: "btn btn-outline-secondary", id: "register-button" do %>
          <i class="far fa-heart text-danger" aria-hidden="true"></i>
            <% end %>
          <% end %>
          </div>
          <% else %>
          <div class="card-footer text-muted d-flex justify-content-between">
            </div>
            <% end %>
      </div>
    <% end %>
    <% else %>
    <h3 class="text-secondary mt-3"><i class="fas fa-search-location text-info"></i> No Reviews To See Yet...</h3>
  <% end %>
</div>